name: M2 Coding Standard
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  static:
    name: M2 Coding Standard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.21.1
        with:
          php-version: 7.4
      - name: Install dependencies
        run: |
          composer global require magento/magento-coding-standard:*
          composer global require phpcompatibility/php-compatibility:*
          composer install
          composer config --list --global
