name: Create Magento Zip Package

on:
  push:
    branches: [ "master" ]
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: montudor/action-zip@v1
      with:
          args: zip -r imagekit_imagekit-magento.zip . -x *.git* -x .github*
    - uses: actions/upload-artifact@v2
      with:
          name: imagekit_imagekit-magento.zip
          path: imagekit_imagekit-magento.zip

